site_name: Python code studies
repo_url: https://github.com/jbcodeforce/python-code
nav:
  - Introduction: 
    - Basic: index.md
    - Summary: python/python-summary.md
    - Advanced: python/faq.md
  - Coding:
    - Development environment: coding/dev-env.md
    - Design patterns: coding/dp.md
    - Code studies: coding/references.md
  - Data & AI:
    - Pandas: data/pandas/index.md
    - Web Data: data/webcrawling/readme.md
    - Python and data sciences: https://jbcodeforce.github.io/ML-studies
  - Web App:
    - FastAPI: fastapi/index.md 
    - Flask studies and basic samples: flask/readme.md
    - Flask Rest microservice with TDD and Docker: flask/flask-tdd-docker.md
    - Flask webapp template with docker: https://github.com/jbcodeforce/python-code/tree/master/Flask/firstRESTapp
    - Pydantic: python/pydantic.md
  - Techno:
    - AWS: techno/aws/index.md
    - Python and Spark: https://jbcodeforce.github.io/spark-studies  
    - Astronomy statistics and image processing: astronomy/README.md
    - Kafka consumer and producer: https://jbcodeforce.github.io/kafka-studies
  - Back to main: https://jbcodeforce.github.io/

theme: 
  name: material
  palette:
    scheme: default
  language: en
  features:
      - content.code.annotate
      - content.tooltips
      # - navigation.tabs
      - navigation.instant
      - navigation.tracking
      # - navigation.sections
      # - navigation.expand
      - navigation.tabs.sticky
      # - navigation.top
  social:
    - type: 'github'
      link: 'https://github.com/jbcodeforce'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jeromeboyer'
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details