site_name: Python code studies
repo_url: https://github.com/jbcodeforce/python-code
nav:
  - Introduction: index.md
  - Development environment: dev-env.md
  - Python:
    - Summary: python/python-summary.md
    - FAQ: python/faq.md
    - Compendium: python/compendium.md
  - Web App with Flask: 
    - Basic samples: flask/readme.md
    - Flask Rest microservice with TDD and Docker: flask/flask-tdd-docker.md
  - Web Data: webcrawling/readme.md
  - Sub-projects:
    - Python studies: https://github.com/jbcodeforce/python-code
    - Python and Spark: https://jbcodeforce.github.io/spark-studies
    - Python and data sciences: https://github.com/jbcodeforce/ml-basics
    - Flask webapp template with docker: https://github.com/jbcodeforce/python-code/angular-flask
    - Kafka consumer and producer: https://github.com/ibm-cloud-architecture/refarch-kc/tree/master/itg-tests


theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences